# Generated by Django 5.2.13 on 2026-04-30 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('name', models.CharField(blank=True, max_length=180)),
                ('os', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('other', 'Autre')], default='android', max_length=12)),
                ('os_version', models.CharField(blank=True, max_length=40)),
                ('app_version', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('revoked', 'Révoqué')], default='active', max_length=10)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_devices', to='accounts.apikey')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_devices', to='sites.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_devices', to='core.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MobileBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('since', models.DateTimeField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='mobile_sync.mobiledevice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SyncSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('pulled_count', models.PositiveIntegerField(default=0)),
                ('pushed_count', models.PositiveIntegerField(default=0)),
                ('conflict_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_sessions', to='mobile_sync.mobiledevice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfflineScanQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('synced', 'Synchronisé'), ('rejected', 'Rejeté'), ('duplicate', 'Doublon')], default='pending', max_length=10)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=240)),
                ('resulting_event_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_queue', to='mobile_sync.mobiledevice')),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['device', 'status'], name='mobile_sync_device__8c5bac_idx')],
            },
        ),
    ]
