[pytest]
DJANGO_SETTINGS_MODULE = kshield.settings.dev
python_files = test_*.py *_test.py tests.py
addopts = --reuse-db --tb=short -p no:cacheprovider
markers =
    integration: tests intégration nécessitant la DB
    unit: tests unitaires purs
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
