# Generated by Django 5.2.13 on 2026-04-30 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raised_at', models.DateTimeField(db_index=True)),
                ('primary_holder_kind', models.CharField(choices=[('employee', 'Employé'), ('worker', 'Ouvrier'), ('visitor', 'Visiteur'), ('unknown', 'Inconnu')], default='unknown', max_length=12)),
                ('primary_holder_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('secondary_holder_kind', models.CharField(blank=True, choices=[('employee', 'Employé'), ('worker', 'Ouvrier'), ('visitor', 'Visiteur'), ('unknown', 'Inconnu')], max_length=12)),
                ('secondary_holder_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Avertissement'), ('critical', 'Critique')], default='warning', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('acknowledged', 'Prise en compte'), ('confirmed', 'Confirmée fraude'), ('dismissed', 'Écartée'), ('escalated', 'Escaladée')], db_index=True, default='open', max_length=14)),
                ('resolution_comment', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-raised_at'],
            },
        ),
        migrations.CreateModel(
            name='FraudInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('in_progress', 'En cours'), ('closed', 'Fermée')], default='open', max_length=14)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('conclusion', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FraudRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=180)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Avertissement'), ('critical', 'Critique')], default='warning', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FraudScoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holder_kind', models.CharField(choices=[('employee', 'Employé'), ('worker', 'Ouvrier'), ('visitor', 'Visiteur')], max_length=12)),
                ('holder_object_id', models.PositiveBigIntegerField()),
                ('score', models.FloatField(default=0.0)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='BLEStillnessSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detected_at', models.DateTimeField(db_index=True)),
                ('immobile_minutes', models.PositiveIntegerField()),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
