# Generated by Django 5.2.13 on 2026-04-30 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0002_initial'),
        ('antifraud', '0001_initial'),
        ('core', '0001_initial'),
        ('devices', '0001_initial'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blestillnesssignal',
            name='helmet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stillness_signals', to='devices.helmet'),
        ),
        migrations.AddField(
            model_name='blestillnesssignal',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blestillnesssignal',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stillness_signals', to='sites.zone'),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fraud_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_alerts', to='access_control.accessevent'),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_fraud_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_alerts', to='sites.site'),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudinvestigation',
            name='alerts',
            field=models.ManyToManyField(blank=True, related_name='investigations', to='antifraud.fraudalert'),
        ),
        migrations.AddField(
            model_name='fraudinvestigation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudinvestigation',
            name='opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigations_opened', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudinvestigation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='fraudinvestigation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudrule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_rules', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='fraudrule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='antifraud.fraudrule'),
        ),
        migrations.AddField(
            model_name='fraudscoring',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudscoring',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_scores', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='fraudscoring',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='fraudrule',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['tenant', 'status', 'severity'], name='antifraud_f_tenant__e48e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['site', 'raised_at'], name='antifraud_f_site_id_a3c540_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fraudscoring',
            unique_together={('tenant', 'holder_kind', 'holder_object_id')},
        ),
    ]
