# Generated by Django 5.2.13 on 2026-04-30 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        ('ouvriers', '0001_initial'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('uid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('type', models.CharField(choices=[('nfc', 'NFC'), ('uhf', 'RFID UHF'), ('uhf_xerafy', 'Xerafy UHF (casque)')], default='nfc', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('lost', 'Perdu'), ('revoked', 'Révoqué'), ('expired', 'Expiré')], default='active', max_length=12)),
                ('holder_kind', models.CharField(choices=[('employee', 'Employé'), ('worker', 'Ouvrier'), ('visitor', 'Visiteur')], max_length=12)),
                ('holder_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=240)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('holder_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='core.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('serial_number', models.CharField(db_index=True, max_length=120, unique=True)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('maintenance', 'Maintenance'), ('lost', 'Perdu / volé')], default='active', max_length=12)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=20)),
                ('firmware_version', models.CharField(blank=True, max_length=40)),
                ('battery_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('commissioned_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='accounts.apikey')),
                ('checkpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='sites.checkpoint')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='sites.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='sites.zone')),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='DeviceHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_online', models.BooleanField(default=True)),
                ('battery_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('signal_strength', models.SmallIntegerField(blank=True, null=True)),
                ('cpu_usage', models.FloatField(blank=True, null=True)),
                ('ram_usage', models.FloatField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='devices.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeviceMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('preventive', 'Préventive'), ('corrective', 'Corrective'), ('replacement', 'Remplacement')], default='corrective', max_length=16)),
                ('technician_name', models.CharField(blank=True, max_length=180)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='devices.device')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=120)),
                ('model', models.CharField(max_length=180)),
                ('type', models.CharField(choices=[('reader_uhf_fixed', 'Lecteur UHF fixe'), ('reader_uhf_mobile', 'Lecteur UHF mobile'), ('reader_nfc_fixed', 'Lecteur NFC fixe'), ('reader_nfc_mobile', 'Lecteur NFC mobile'), ('tag_uhf', 'Tag RFID UHF'), ('beacon_ble', 'Beacon BLE'), ('tablet', 'Tablette'), ('smartphone', 'Smartphone'), ('id_scanner', "Scanner pièce d'identité"), ('door_lock', 'Gâche électrique'), ('camera', 'Caméra'), ('portique', 'Portique RFID')], max_length=24)),
                ('spec', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['brand', 'model'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='devices.devicemodel'),
        ),
        migrations.CreateModel(
            name='FirmwareVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=40)),
                ('release_notes', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='firmwares/')),
                ('is_published', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmwares', to='devices.devicemodel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Helmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('serial_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('uhf_tag_uid', models.CharField(max_length=64, unique=True)),
                ('ble_beacon_uid', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('maintenance', 'Maintenance'), ('retired', 'Hors service'), ('lost', 'Perdu')], default='active', max_length=16)),
                ('size', models.CharField(blank=True, max_length=8)),
                ('commissioned_at', models.DateField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_battery_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('current_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_helmets', to='ouvriers.worker')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helmets', to='core.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BadgeHelmetPairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pairing_date', models.DateField(db_index=True)),
                ('first_scan_at', models.DateTimeField()),
                ('last_verified_at', models.DateTimeField()),
                ('verifications_count', models.PositiveIntegerField(default=1)),
                ('is_broken', models.BooleanField(default=False)),
                ('broken_reason', models.CharField(blank=True, max_length=240)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='devices.badge')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='sites.site')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='ouvriers.worker')),
                ('helmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='devices.helmet')),
            ],
            options={
                'ordering': ['-pairing_date'],
            },
        ),
        migrations.CreateModel(
            name='OTAUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('scheduled', 'Programmée'), ('in_progress', 'En cours'), ('succeeded', 'Réussie'), ('failed', 'Échec'), ('cancelled', 'Annulée')], default='scheduled', max_length=16)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ota_updates', to='devices.device')),
                ('firmware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='devices.firmwareversion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['tenant', 'status', 'type'], name='devices_bad_tenant__e24ecc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicemodel',
            unique_together={('brand', 'model')},
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['tenant', 'status'], name='devices_dev_tenant__0c16ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='firmwareversion',
            unique_together={('device_model', 'version')},
        ),
        migrations.AddIndex(
            model_name='badgehelmetpairing',
            index=models.Index(fields=['badge', 'helmet', 'pairing_date'], name='devices_bad_badge_i_011712_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='badgehelmetpairing',
            unique_together={('worker', 'pairing_date', 'site')},
        ),
    ]
