# Generated by Django 4.2.30 on 2026-05-07 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitors', '0001_initial'),
        ('sites', '0001_initial'),
        ('access_control', '0003_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holder_kind', models.CharField(choices=[('employee', 'Employé'), ('worker', 'Ouvrier'), ('visitor', 'Visiteur')], max_length=12)),
                ('holder_object_id', models.PositiveBigIntegerField()),
                ('holder_label', models.CharField(help_text="Snapshot du nom du porteur (au cas où l'objet est supprimé).", max_length=240)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, help_text='Date à laquelle le badge a été rendu / désassigné.', null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='BadgeScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('decision', models.CharField(choices=[('granted', 'Autorisé'), ('denied', 'Refusé'), ('review', 'À vérifier')], max_length=8)),
                ('method', models.CharField(blank=True, max_length=8)),
                ('denial_reason', models.CharField(blank=True, max_length=240)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='badge',
            name='category',
            field=models.CharField(choices=[('visitor_qr', 'Badge visiteur QR'), ('employee_rfid', 'Badge employé RFID'), ('worker_rfid', 'Badge ouvrier RFID (avec casque)')], default='employee_rfid', help_text='Workflow métier auquel appartient le badge.', max_length=20),
        ),
        migrations.AddField(
            model_name='badge',
            name='last_scan_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Mis à jour automatiquement par signal sur AccessEvent.', null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='paired_helmet',
            field=models.ForeignKey(blank=True, help_text='Casque associé pour le couplage badge+casque (chantier).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paired_badges', to='devices.helmet'),
        ),
        migrations.AddField(
            model_name='badge',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Badge imprimable au format PDF avec QR code.', null=True, upload_to='badges/pdf/'),
        ),
        migrations.AddField(
            model_name='badge',
            name='qr_payload',
            field=models.CharField(blank=True, help_text='Données encodées dans le QR code (visit ID, RFID UID, etc.)', max_length=240),
        ),
        migrations.AddField(
            model_name='badge',
            name='scan_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='badge',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='suspended_reason',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='badge',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Miniature PNG du badge (générée automatiquement avec le PDF).', null=True, upload_to='badges/thumbnails/'),
        ),
        migrations.AddField(
            model_name='badge',
            name='valid_from',
            field=models.DateField(blank=True, help_text='Début de validité — le badge est refusé avant cette date.', null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Fin de validité — le badge passe automatiquement en `expired`.', null=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='holder_kind',
            field=models.CharField(blank=True, choices=[('employee', 'Employé'), ('worker', 'Ouvrier'), ('visitor', 'Visiteur')], max_length=12),
        ),
        migrations.AlterField(
            model_name='badge',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible (en pool)'), ('assigned', 'Attribué'), ('active', 'Actif'), ('suspended', 'Suspendu'), ('expired', 'Expiré'), ('lost', 'Perdu'), ('revoked', 'Révoqué'), ('disabled', 'Désactivé')], default='active', max_length=12),
        ),
        migrations.AlterField(
            model_name='badge',
            name='type',
            field=models.CharField(choices=[('nfc', 'NFC'), ('uhf', 'RFID UHF'), ('uhf_xerafy', 'Xerafy UHF (casque)'), ('qr', 'QR Code')], default='nfc', max_length=16),
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['category', 'status'], name='devices_bad_categor_8b3908_idx'),
        ),
        migrations.AddField(
            model_name='badgescanevent',
            name='access_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_scan_events', to='access_control.accessevent'),
        ),
        migrations.AddField(
            model_name='badgescanevent',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_events', to='devices.badge'),
        ),
        migrations.AddField(
            model_name='badgescanevent',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badge_scans', to='sites.site'),
        ),
        migrations.AddField(
            model_name='badgeassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text="Agent ayant effectué l'attribution.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badge_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='badgeassignment',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='devices.badge'),
        ),
        migrations.AddField(
            model_name='badgeassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='badgeassignment',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badge_assignments_released', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='badgeassignment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='badgeassignment',
            name='visit_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badge_assignments', to='visitors.visitrequest'),
        ),
        migrations.AddIndex(
            model_name='badgescanevent',
            index=models.Index(fields=['badge', '-timestamp'], name='devices_bad_badge_i_c799c3_idx'),
        ),
        migrations.AddIndex(
            model_name='badgeassignment',
            index=models.Index(fields=['badge', '-assigned_at'], name='devices_bad_badge_i_7afb11_idx'),
        ),
        migrations.AddIndex(
            model_name='badgeassignment',
            index=models.Index(fields=['holder_kind', 'holder_object_id'], name='devices_bad_holder__16809b_idx'),
        ),
    ]
