# Generated by Django 6.0.5 on 2026-05-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_camera_password_encrypted"),
        (
            "devices",
            "0004_rename_cam_site_status_idx_devices_cam_site_id_4fe4ae_idx_and_more",
        ),
    ]

    operations = []
