# Generated by Django 5.2.14 on 2026-07-09 11:21

import core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0002_company_logo_sitegateway"),
        ("devices", "0006_devicemodel_face_terminal_type"),
        ("sites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Nom donné à l'agent, ex. « Chantier Riviera-01 ».",
                        max_length=120,
                    ),
                ),
                (
                    "api_token",
                    models.CharField(
                        db_index=True,
                        help_text="Secret partagé pour authentifier l'agent (HMAC).",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "hmac_secret",
                    core.fields.EncryptedCharField(
                        blank=True,
                        help_text="Secret HMAC pour signer les messages.",
                        max_length=128,
                    ),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connected",
                    models.BooleanField(
                        default=False,
                        help_text="True si une WS est actuellement ouverte.",
                    ),
                ),
                (
                    "channel_name",
                    models.CharField(
                        blank=True,
                        help_text="Nom Channels du canal WS actif.",
                        max_length=200,
                    ),
                ),
                ("version", models.CharField(blank=True, max_length=32)),
                ("os_info", models.CharField(blank=True, max_length=120)),
                (
                    "devices_discovered",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Snapshot des équipements vus par l'agent.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="local_agents",
                        to="sites.site",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="local_agents",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen_at"],
            },
        ),
        migrations.CreateModel(
            name="RFIDEnrollmentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("single", "Unitaire"), ("bulk", "En masse")],
                        default="single",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En préparation"),
                            ("listening", "En écoute"),
                            ("completed", "Terminée"),
                            ("cancelled", "Annulée"),
                            ("timeout", "Timeout"),
                            ("error", "Erreur"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "holder_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("worker", "Ouvrier"),
                            ("employee", "Employé"),
                            ("visitor", "Visiteur"),
                            ("", "Aucun (pool)"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "holder_object_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "timeout_seconds",
                    models.PositiveIntegerField(
                        default=180, help_text="Auto-annulation si inactivité."
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("scans_count", models.PositiveIntegerField(default=0)),
                ("valid_count", models.PositiveIntegerField(default=0)),
                ("duplicate_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.CharField(blank=True, max_length=500)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "holder_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rfid_enrollment_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reader",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lecteur cible ; null = tous lecteurs du tenant.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rfid_sessions",
                        to="devices.device",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="sites.site",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rfid_enrollment_sessions",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="sites.zone",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RFIDEnrollmentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("card.detected", "Carte détectée"),
                            ("card.duplicate", "Carte déjà enrôlée"),
                            ("card.enrolled", "Carte enrôlée"),
                            ("card.error", "Erreur carte"),
                            ("session.start", "Session démarrée"),
                            ("session.stop", "Session arrêtée"),
                            ("session.timeout", "Session timeout"),
                            ("device.error", "Erreur équipement"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("uid", models.CharField(blank=True, db_index=True, max_length=64)),
                ("rssi", models.SmallIntegerField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("message", models.CharField(blank=True, max_length=240)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="devices.device",
                    ),
                ),
                (
                    "resulting_badge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="devices.badge",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="devices.rfidenrollmentsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeviceCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PING_DEVICE", "Ping"),
                            ("SYNC_DEVICE", "Synchronisation"),
                            ("RESTART_DEVICE", "Redémarrage"),
                            ("GET_DEVICE_INFO", "Info équipement"),
                            ("GET_DEVICE_STATUS", "Statut équipement"),
                            ("GET_DEVICE_LOGS", "Logs équipement"),
                            ("START_RFID_ENROLLMENT", "Démarrer écoute RFID"),
                            ("STOP_RFID_ENROLLMENT", "Arrêter écoute RFID"),
                            ("READ_RFID_CARD", "Lire carte RFID"),
                            ("PUSH_USER", "Push utilisateur (biométrie)"),
                            ("CUSTOM", "Commande custom"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Paramètres additionnels (ex. timeout, session_id).",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("sent", "Envoyée"),
                            ("acknowledged", "Acquittée"),
                            ("completed", "Terminée"),
                            ("failed", "Échec"),
                            ("timeout", "Timeout"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("acked_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "timeout_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deadline avant passage en statut timeout.",
                        null=True,
                    ),
                ),
                (
                    "response_raw",
                    models.JSONField(
                        blank=True, default=dict, help_text="Réponse brute du device."
                    ),
                ),
                (
                    "response_normalized",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Version normalisée pour le front.",
                    ),
                ),
                ("error_message", models.CharField(blank=True, max_length=500)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="devices.device",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_device_commands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_commands",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        help_text="Session d'enrôlement qui a émis cette commande.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commands",
                        to="devices.rfidenrollmentsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("agent_offline", "Agent hors ligne"),
                            ("agent_stale", "Agent stale"),
                            ("device_offline", "Équipement hors ligne"),
                            ("session_stalled", "Session bloquée"),
                            ("command_timeout", "Commande timeout"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critique"),
                            ("warning", "Avertissement"),
                            ("info", "Info"),
                        ],
                        db_index=True,
                        default="warning",
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(max_length=240)),
                ("detail", models.CharField(blank=True, max_length=500)),
                ("target_url", models.CharField(blank=True, max_length=240)),
                (
                    "target_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("routed_at", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_alerts",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="rfidenrollmentsession",
            index=models.Index(
                fields=["tenant", "status"], name="devices_rfi_tenant__10f171_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rfidenrollmentsession",
            index=models.Index(
                fields=["initiated_by", "status"], name="devices_rfi_initiat_e87512_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rfidenrollmentevent",
            index=models.Index(
                fields=["session", "event_type"], name="devices_rfi_session_14249b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rfidenrollmentevent",
            index=models.Index(fields=["uid"], name="devices_rfi_uid_e9db4e_idx"),
        ),
        migrations.AddIndex(
            model_name="devicecommand",
            index=models.Index(
                fields=["tenant", "device", "status"],
                name="devices_dev_tenant__6ce927_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="devicecommand",
            index=models.Index(
                fields=["kind", "status"], name="devices_dev_kind_b9c607_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemalert",
            index=models.Index(
                fields=["tenant", "kind", "resolved_at"],
                name="devices_sys_tenant__a2043b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="systemalert",
            index=models.Index(
                fields=["severity", "resolved_at"],
                name="devices_sys_severit_225c98_idx",
            ),
        ),
    ]
