# Generated by Django 5.2.14 on 2026-07-09 13:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_company_logo_sitegateway"),
        (
            "devices",
            "0007_localagent_rfidenrollmentsession_rfidenrollmentevent_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="localagent",
            name="activated_at",
            field=models.DateTimeField(
                blank=True, help_text="Date du premier appairage réussi.", null=True
            ),
        ),
        migrations.AddField(
            model_name="localagent",
            name="activation_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Expiration du activation_token — après quoi il faut regénérer.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="localagent",
            name="activation_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Token à usage unique pour l'enrôlement initial du Gateway (échangé contre api_token permanent au premier boot).",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="localagent",
            name="cloud_status",
            field=models.CharField(
                choices=[
                    ("unknown", "Inconnu"),
                    ("ok", "OK"),
                    ("degraded", "Dégradé"),
                    ("down", "Hors service"),
                ],
                default="unknown",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="localagent",
            name="events_pending",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Nombre d'événements dans l'offline queue de l'agent.",
            ),
        ),
        migrations.AddField(
            model_name="localagent",
            name="ip_local",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP locale de la machine hôte, poussée par l'agent au heartbeat.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="localagent",
            name="ip_public",
            field=models.GenericIPAddressField(
                blank=True, help_text="IP publique vue par le serveur cloud.", null=True
            ),
        ),
        migrations.AddField(
            model_name="localagent",
            name="mqtt_status",
            field=models.CharField(
                choices=[
                    ("unknown", "Inconnu"),
                    ("ok", "OK"),
                    ("degraded", "Dégradé"),
                    ("down", "Hors service"),
                ],
                default="unknown",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="localagent",
            name="revoked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date de révocation — l'agent ne peut plus se connecter.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="localagent",
            name="uptime_seconds",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="localagent",
            name="ws_status",
            field=models.CharField(
                choices=[
                    ("unknown", "Inconnu"),
                    ("ok", "OK"),
                    ("degraded", "Dégradé"),
                    ("down", "Hors service"),
                ],
                default="unknown",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="DeviceTwin",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="twin",
                        serialize=False,
                        to="devices.device",
                    ),
                ),
                ("reachable", models.BooleanField(db_index=True, default=False)),
                (
                    "health_score",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=100,
                        help_text="Score 0-100 recalculé à chaque refresh (0=KO, 100=OK).",
                    ),
                ),
                (
                    "health_reasons",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste des raisons ayant fait baisser le score.",
                    ),
                ),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("uptime_seconds", models.BigIntegerField(blank=True, null=True)),
                ("cpu_percent", models.FloatField(blank=True, null=True)),
                ("ram_percent", models.FloatField(blank=True, null=True)),
                ("storage_percent", models.FloatField(blank=True, null=True)),
                ("temperature_c", models.FloatField(blank=True, null=True)),
                (
                    "battery_percent",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "network_quality",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="0-100 (RSSI ou latence normalisée).",
                        null=True,
                    ),
                ),
                ("firmware", models.CharField(blank=True, max_length=64)),
                ("hardware", models.CharField(blank=True, max_length=64)),
                (
                    "recent_errors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Max 20 dernières erreurs (ring buffer).",
                    ),
                ),
                (
                    "driver_class",
                    models.CharField(
                        blank=True,
                        help_text="Nom du driver qui alimente ce twin.",
                        max_length=120,
                    ),
                ),
                ("raw_status", models.JSONField(blank=True, default=dict)),
                (
                    "last_probed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Dernier moment où l'équipement a répondu à un ping.",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["reachable", "health_score"],
                        name="devices_dev_reachab_197136_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EdgeGatewayPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text='Nom convivial, ex. "kshield-edge-1.2.0-windows-x64".',
                        max_length=120,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("linux_deb", "Linux (.deb)"),
                            ("linux_rpm", "Linux (.rpm)"),
                            ("linux_sh", "Linux (script)"),
                            ("docker", "Docker"),
                            ("raspberry_pi", "Raspberry Pi"),
                            ("mini_pc", "Mini PC industriel"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "version",
                    models.CharField(help_text='Semver, ex. "1.2.0".', max_length=32),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Binaire installateur ou tarball. Null pour Docker (image seule).",
                        null=True,
                        upload_to="gateway_packages/",
                    ),
                ),
                (
                    "docker_image",
                    models.CharField(
                        blank=True,
                        help_text='Ex. "kaydangroupe/kshield-edge:1.2.0" pour la plateforme "docker".',
                        max_length=200,
                    ),
                ),
                (
                    "docker_compose_snippet",
                    models.TextField(
                        blank=True,
                        help_text="Extrait docker-compose.yml prêt à coller.",
                    ),
                ),
                ("size_bytes", models.BigIntegerField(default=0)),
                (
                    "checksum_sha256",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("release_notes", models.TextField(blank=True)),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "is_latest",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Marque la version courante pour chaque plateforme.",
                    ),
                ),
                (
                    "min_os_version",
                    models.CharField(
                        blank=True,
                        help_text='Ex. "Windows 10 20H2" ou "Ubuntu 20.04".',
                        max_length=64,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "platform"],
                "indexes": [
                    models.Index(
                        fields=["platform", "is_latest"],
                        name="devices_edg_platfor_e9815e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("battery_low", "Batterie faible"),
                            ("battery_critical", "Batterie critique"),
                            ("storage_low", "Stockage faible"),
                            ("storage_critical", "Stockage critique"),
                            ("temperature_high", "Température élevée"),
                            ("temperature_critical", "Température critique"),
                            ("firmware_outdated", "Firmware obsolète"),
                            ("connectivity_loss", "Perte de connectivité"),
                            ("high_error_rate", "Taux d'erreurs élevé"),
                            ("performance_drop", "Baisse de performance"),
                            ("scheduled", "Maintenance programmée"),
                            ("manual", "Ticket manuel"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Avertissement"),
                            ("critical", "Critique"),
                        ],
                        db_index=True,
                        default="warning",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Ouvert"),
                            ("in_progress", "En cours"),
                            ("resolved", "Résolu"),
                            ("cancelled", "Annulé"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True)),
                (
                    "prediction",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Données prédictives : trend, ETA, seuils.",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=1.0,
                        help_text="0.0-1.0 — confiance du moteur pour les tickets auto.",
                    ),
                ),
                (
                    "created_by_engine",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_tickets",
                        to="devices.device",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_tickets",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status", "severity"],
                        name="devices_mai_tenant__d06d86_idx",
                    ),
                    models.Index(
                        fields=["device", "status"],
                        name="devices_mai_device__3a0d8b_idx",
                    ),
                ],
            },
        ),
    ]
