# Generated by Django 5.2.14 on 2026-07-21 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0005_remove_accessevent_acc_evt_site_ts_idx_and_more'),
        ('core', '0002_company_logo_sitegateway'),
        ('devices', '0017_edge_model_audit_fields'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicediscovery',
            new_name='devices_dev_tenant__1c494c_idx',
            old_name='discovery_ten_st_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='devicediscovery',
            new_name='devices_dev_gateway_ecba6b_idx',
            old_name='discovery_gw_st_idx',
        ),
        migrations.RenameIndex(
            model_name='devicediscovery',
            new_name='devices_dev_compati_4fb03d_idx',
            old_name='discovery_cp_st_idx',
        ),
        migrations.RenameIndex(
            model_name='devicediscovery',
            new_name='devices_dev_vendor_e2c7bf_idx',
            old_name='discovery_vd_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='devicediscoveryscan',
            new_name='devices_dev_tenant__b1fd7a_idx',
            old_name='discovery_scan_ten_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='devicediscoveryscan',
            new_name='devices_dev_gateway_47ddbd_idx',
            old_name='discovery_scan_gw_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='deviceevent',
            new_name='devices_dev_tenant__1946da_idx',
            old_name='dev_ev_tenant_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='deviceevent',
            new_name='devices_dev_site_id_e7cd9c_idx',
            old_name='dev_ev_site_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='deviceevent',
            new_name='devices_dev_event_t_bfb983_idx',
            old_name='dev_ev_type_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='deviceevent',
            new_name='devices_dev_severit_cf6f95_idx',
            old_name='dev_ev_sev_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='deviceevent',
            new_name='devices_dev_result_5b1643_idx',
            old_name='dev_ev_res_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='deviceevent',
            new_name='devices_dev_gateway_7ffea8_idx',
            old_name='dev_ev_gw_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='deviceevent',
            new_name='devices_dev_device__a4bf31_idx',
            old_name='dev_ev_dev_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='deviceevent',
            new_name='devices_dev_is_offl_a738f1_idx',
            old_name='dev_ev_off_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='deviceevent',
            new_name='devices_dev_is_sync_fceebc_idx',
            old_name='dev_ev_sync_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='deviceevent',
            new_name='devices_dev_transmi_ddfa69_idx',
            old_name='dev_ev_mode_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='edgesyncbatch',
            new_name='devices_edg_gateway_3af6bd_idx',
            old_name='edgesync_bt_gw_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='edgesyncbatch',
            new_name='devices_edg_tenant__78eca5_idx',
            old_name='edgesync_bt_ts_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='edgesyncbatch',
            new_name='devices_edg_priorit_625d70_idx',
            old_name='edgesync_bt_pr_st_idx',
        ),
        migrations.RenameIndex(
            model_name='edgesyncbatch',
            new_name='devices_edg_directi_dbea60_idx',
            old_name='edgesync_bt_dr_st_idx',
        ),
        migrations.RenameIndex(
            model_name='edgesyncconflict',
            new_name='devices_edg_resolut_ff68ec_idx',
            old_name='edgesync_cf_rs_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='edgesyncconflict',
            new_name='devices_edg_entity__d9f94f_idx',
            old_name='edgesync_cf_et_ek_idx',
        ),
        migrations.RenameIndex(
            model_name='edgesyncconflict',
            new_name='devices_edg_tenant__f95592_idx',
            old_name='edgesync_cf_tn_rs_idx',
        ),
        migrations.RenameIndex(
            model_name='edgesyncitem',
            new_name='devices_edg_batch_i_191410_idx',
            old_name='edgesync_it_bt_st_idx',
        ),
        migrations.RenameIndex(
            model_name='edgesyncitem',
            new_name='devices_edg_entity__dc7124_idx',
            old_name='edgesync_it_et_ek_idx',
        ),
        migrations.RenameIndex(
            model_name='edgesyncitem',
            new_name='devices_edg_payload_b354aa_idx',
            old_name='edgesync_it_ph_idx',
        ),
        migrations.RenameIndex(
            model_name='eventacknowledgement',
            new_name='devices_eve_event_i_dd1b68_idx',
            old_name='dev_ev_ack_evt_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='eventacknowledgement',
            new_name='devices_eve_action_22dd4b_idx',
            old_name='dev_ev_ack_act_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='eventtype',
            new_name='devices_eve_categor_abc277_idx',
            old_name='devevent_type_cat_active_idx',
        ),
        migrations.RenameIndex(
            model_name='eventtype',
            new_name='devices_eve_severit_996b75_idx',
            old_name='devevent_type_sev_idx',
        ),
        migrations.RenameIndex(
            model_name='localagentconfiguration',
            new_name='devices_loc_agent_i_0d77e0_idx',
            old_name='agent_cf_ag_vr_idx',
        ),
        migrations.RenameIndex(
            model_name='localagentconfiguration',
            new_name='devices_loc_agent_i_11ffdf_idx',
            old_name='agent_cf_ag_cur_idx',
        ),
        migrations.RenameIndex(
            model_name='localagentheartbeat',
            new_name='devices_loc_agent_i_7ca570_idx',
            old_name='agent_hb_ag_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='localagentheartbeat',
            new_name='devices_loc_tenant__fd5c81_idx',
            old_name='agent_hb_ten_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='localagentheartbeat',
            new_name='devices_loc_state_738739_idx',
            old_name='agent_hb_st_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='localagentlog',
            new_name='devices_loc_agent_i_24f9b7_idx',
            old_name='agent_log_ag_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='localagentlog',
            new_name='devices_loc_level_ac0309_idx',
            old_name='agent_log_lv_ts_idx',
        ),
        migrations.AlterField(
            model_name='devicediscovery',
            name='adopted_by',
            field=models.CharField(blank=True, help_text='User qui a adopté (email). Textuel pour survivre à la suppression.', max_length=200),
        ),
        migrations.AlterField(
            model_name='devicediscovery',
            name='adopted_device',
            field=models.OneToOneField(blank=True, help_text='Device officiel créé après adoption.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_origin', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='devicediscovery',
            name='compatibility',
            field=models.CharField(choices=[('compatible', 'Compatible officiel'), ('experimental', 'Compatible (expérimental)'), ('unsupported', 'Non supporté (générique)'), ('incompatible', 'Incompatible (protocole inconnu)'), ('unknown', 'Inconnu (test requis)')], default='unknown', max_length=16),
        ),
        migrations.AlterField(
            model_name='devicediscovery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='devicediscovery',
            name='detected_via',
            field=models.CharField(choices=[('arp', 'ARP'), ('mdns', 'mDNS / Bonjour'), ('ssdp', 'SSDP / UPnP'), ('onvif', 'ONVIF'), ('snmp', 'SNMP'), ('nmap', 'Nmap'), ('ble', 'Bluetooth LE'), ('usb', 'USB / Série'), ('manual', 'Saisie manuelle'), ('qr', "QR code d'activation"), ('token', 'Token enrôlement'), ('unknown', 'Inconnu')], default='unknown', help_text="Protocole qui a détecté l'équipement en premier.", max_length=12),
        ),
        migrations.AlterField(
            model_name='devicediscovery',
            name='device_type',
            field=models.CharField(blank=True, help_text='Ex: "ip_camera", "rfid_reader", "biometric_terminal", "controller"', max_length=32),
        ),
        migrations.AlterField(
            model_name='devicediscovery',
            name='gateway',
            field=models.ForeignKey(blank=True, help_text="Gateway locale ayant détecté l'équipement.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discoveries', to='devices.localagent'),
        ),
        migrations.AlterField(
            model_name='devicediscovery',
            name='latency_ms',
            field=models.PositiveIntegerField(default=0, help_text='Latence moyenne du dernier ping (ms).'),
        ),
        migrations.AlterField(
            model_name='devicediscovery',
            name='mac_address',
            field=models.CharField(blank=True, db_index=True, help_text='Format "AA:BB:CC:DD:EE:FF" — clé principale de dédup.', max_length=17),
        ),
        migrations.AlterField(
            model_name='devicediscovery',
            name='ports_open',
            field=models.JSONField(blank=True, default=list, help_text='Ports utiles ouverts détectés (ex: [80, 443, 554, 8080]).'),
        ),
        migrations.AlterField(
            model_name='devicediscovery',
            name='protocols_supported',
            field=models.JSONField(blank=True, default=list, help_text='Ex: ["onvif", "rtsp", "http"] — détectés au scan.'),
        ),
        migrations.AlterField(
            model_name='devicediscovery',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Payload brut du scan (pour debug + réplay).'),
        ),
        migrations.AlterField(
            model_name='devicediscovery',
            name='scan',
            field=models.ForeignKey(blank=True, help_text='Session de scan qui a détecté cet équipement en premier.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discoveries', to='devices.devicediscoveryscan'),
        ),
        migrations.AlterField(
            model_name='devicediscovery',
            name='signal_strength',
            field=models.IntegerField(blank=True, help_text='Force du signal en dBm (pour BLE/WiFi uniquement).', null=True),
        ),
        migrations.AlterField(
            model_name='devicediscovery',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site auto-détecté (via gateway rattachée).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discoveries', to='sites.site'),
        ),
        migrations.AlterField(
            model_name='devicediscovery',
            name='status',
            field=models.CharField(choices=[('detected', 'Détecté (info brute uniquement)'), ('tested', 'Testé (connexion validée)'), ('adopted', 'Adopté (Device créé)'), ('rejected', 'Rejeté (ignoré définitivement)'), ('stale', 'Périmé (plus vu récemment)')], db_index=True, default='detected', max_length=12),
        ),
        migrations.AlterField(
            model_name='devicediscovery',
            name='suggested_driver',
            field=models.CharField(blank=True, help_text='Ex: "hikvision", "zkteco", "onvif_generic".', max_length=40),
        ),
        migrations.AlterField(
            model_name='devicediscovery',
            name='times_seen',
            field=models.PositiveIntegerField(default=1, help_text="Nombre de fois où l'équipement a été détecté."),
        ),
        migrations.AlterField(
            model_name='devicediscovery',
            name='vendor',
            field=models.CharField(blank=True, db_index=True, help_text='Ex: Hikvision, ZKTeco, Axis. Déduit du OUI MAC ou du protocole.', max_length=64),
        ),
        migrations.AlterField(
            model_name='devicediscoveryscan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='devicediscoveryscan',
            name='gateway',
            field=models.ForeignKey(blank=True, help_text='Gateway ayant lancé le scan (null = scan cloud/admin).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_scans', to='devices.localagent'),
        ),
        migrations.AlterField(
            model_name='devicediscoveryscan',
            name='protocols_used',
            field=models.JSONField(blank=True, default=list, help_text='Liste des protocoles activés (ex: ["arp", "onvif"]).'),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='access_event',
            field=models.OneToOneField(blank=True, help_text="Si l'événement a déclenché une décision d'accès métier.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_event', to='access_control.accessevent'),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent local (peut être un sous-agent RFID/BLE spécialisé).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_local', to='devices.localagent'),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='driver_code',
            field=models.CharField(blank=True, help_text='Ex: "hikvision", "zkteco", "onvif".', max_length=40),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='gateway',
            field=models.ForeignKey(blank=True, help_text="Gateway Edge ayant relayé l'événement (peut différer du device).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_via_gateway', to='devices.localagent'),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='holder_ref',
            field=models.CharField(blank=True, help_text='ID textuel de la personne — "EMP-1234" / "VIS-9".', max_length=64),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Hash unique pour dédupliquer les rejeus MQTT/WS.', max_length=64),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='is_offline',
            field=models.BooleanField(db_index=True, default=False, help_text="True si l'événement a été mis en queue offline avant transmission."),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='is_synced',
            field=models.BooleanField(db_index=True, default=True, help_text="False si l'événement provient d'un batch de sync différée et attend encore une confirmation cloud."),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='message',
            field=models.TextField(blank=True, help_text="Résumé humain de l'événement — 1 ligne max."),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='occurred_at',
            field=models.DateTimeField(db_index=True, help_text="Timestamp d'origine (device ou driver)."),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='payload',
            field=models.JSONField(blank=True, default=dict, help_text='Payload driver brut — pour debug + réplay.'),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Snapshot MinIO/S3 si dispo (caméra, biométrique).'),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp de réception par le serveur cloud.'),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='sync_batch_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID du batch de synchronisation ayant remonté cet event.', max_length=64),
        ),
        migrations.AlterField(
            model_name='edgesyncbatch',
            name='batch_id',
            field=models.CharField(db_index=True, help_text="ID généré par l'agent (ex: uuid+timestamp).", max_length=64),
        ),
        migrations.AlterField(
            model_name='edgesyncbatch',
            name='checksum_algorithm',
            field=models.CharField(default='sha256', help_text='Algo utilisé (sha256 obligatoire, blake3 pour perf).', max_length=16),
        ),
        migrations.AlterField(
            model_name='edgesyncbatch',
            name='checksum_computed',
            field=models.CharField(blank=True, help_text='Hash recalculé côté serveur après réception complète.', max_length=128),
        ),
        migrations.AlterField(
            model_name='edgesyncbatch',
            name='checksum_declared',
            field=models.CharField(blank=True, help_text="Hash annoncé par l'agent au start (checksum de tout le batch).", max_length=128),
        ),
        migrations.AlterField(
            model_name='edgesyncbatch',
            name='compression',
            field=models.CharField(blank=True, choices=[('', 'Aucune'), ('gzip', 'gzip'), ('zstd', 'zstd')], max_length=16),
        ),
        migrations.AlterField(
            model_name='edgesyncbatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='edgesyncbatch',
            name='encryption',
            field=models.CharField(blank=True, help_text='Ex: "AES-256-GCM" — vide = TLS uniquement.', max_length=32),
        ),
        migrations.AlterField(
            model_name='edgesyncbatch',
            name='items_declared',
            field=models.PositiveIntegerField(default=0, help_text="Nombre d'items annoncés par l'agent au start."),
        ),
        migrations.AlterField(
            model_name='edgesyncbatch',
            name='priority',
            field=models.CharField(choices=[('low', 'Basse (config, catalogues)'), ('normal', 'Normale (events routiniers)'), ('high', 'Haute (badges révoqués)'), ('critical', 'Critique (alertes, fraudes)')], db_index=True, default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='edgesyncbatch',
            name='resume_from_offset',
            field=models.PositiveIntegerField(default=0, help_text='Offset (en items) où reprendre après crash. 0 = début.'),
        ),
        migrations.AlterField(
            model_name='edgesyncconflict',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='edgesyncconflict',
            name='resolution',
            field=models.CharField(choices=[('pending', 'En attente de résolution'), ('cloud_wins', 'Cloud a raison (écrase local)'), ('edge_wins', 'Edge a raison (écrase cloud)'), ('merge', 'Fusion manuelle appliquée'), ('ignore', 'Conflit ignoré (accepté tel quel)'), ('escalated', 'Escaladé à admin humain')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='edgesyncitem',
            name='entity_key',
            field=models.CharField(db_index=True, help_text="Clé unique de l'entité côté Edge (ex: UUID event, uid badge).", max_length=128),
        ),
        migrations.AlterField(
            model_name='edgesyncitem',
            name='entity_type',
            field=models.CharField(choices=[('event', 'Événement technique'), ('access_event', "Événement d'accès"), ('alert', 'Alerte système'), ('badge', 'Badge'), ('badge_assignment', 'Attribution de badge'), ('badge_revocation', 'Révocation de badge'), ('helmet', 'Casque BLE'), ('employee', 'Employé'), ('worker', 'Ouvrier'), ('visitor', 'Visiteur'), ('access_rule', "Règle d'accès"), ('site', 'Site'), ('zone', 'Zone'), ('checkpoint', "Point d'accès"), ('device', 'Équipement'), ('device_config', 'Config équipement'), ('offline_log', 'Journal offline')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='edgesyncitem',
            name='entity_version',
            field=models.PositiveIntegerField(default=1, help_text="Version de l'entité côté Edge — permet détection conflit."),
        ),
        migrations.AlterField(
            model_name='edgesyncitem',
            name='payload_hash',
            field=models.CharField(blank=True, help_text='SHA256 du payload — pour dédup + intégrité.', max_length=64),
        ),
        migrations.AlterField(
            model_name='edgesyncitem',
            name='resolved_object_id',
            field=models.CharField(blank=True, help_text="PK cloud de l'objet créé/modifié suite à ce sync.", max_length=64),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='code',
            field=models.CharField(db_index=True, help_text='Code stable ex: "ACCESS_GRANTED", "DOOR_FORCED".', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='color',
            field=models.CharField(blank=True, help_text='Classe Tailwind ou hex — ex: "text-danger", "#f97316".', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='description',
            field=models.TextField(blank=True, help_text='Description détaillée pour tooltip / documentation.'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='icon',
            field=models.CharField(blank=True, help_text='Nom lucide-react (ex: "shield-alert", "door-open").', max_length=40),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False pour désactiver un type sans le supprimer.'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='is_system',
            field=models.BooleanField(default=False, help_text='True pour les 69 types de base — protégés contre suppression accidentelle.'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='label',
            field=models.CharField(help_text="Libellé affiché en français dans l'UI.", max_length=140),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='requires_ack',
            field=models.BooleanField(default=False, help_text="Requiert un acquittement humain (bouton dans l'UI)."),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='severity_default',
            field=models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('critical', 'Critique'), ('emergency', 'Urgence')], default='info', help_text="Sévérité par défaut si l'événement ne la précise pas.", max_length=12),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='triggers_alert',
            field=models.BooleanField(default=False, help_text='Génère automatiquement une SystemAlert quand reçu.'),
        ),
        migrations.AlterField(
            model_name='localagentconfiguration',
            name='checksum',
            field=models.CharField(blank=True, help_text='SHA256 du payload pour dédup + intégrité.', max_length=64),
        ),
        migrations.AlterField(
            model_name='localagentconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='localagentconfiguration',
            name='is_current',
            field=models.BooleanField(db_index=True, default=False, help_text="True = version en cours d'usage par l'agent."),
        ),
        migrations.AlterField(
            model_name='localagentconfiguration',
            name='is_draft',
            field=models.BooleanField(default=True, help_text='True = brouillon non-encore appliqué.'),
        ),
        migrations.AlterField(
            model_name='localagentconfiguration',
            name='payload',
            field=models.JSONField(blank=True, default=dict, help_text='Config JSON complète (env, params vendor, timeouts, etc.)'),
        ),
        migrations.AlterField(
            model_name='localagentconfiguration',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Compteur incrémental — auto-géré à chaque save.'),
        ),
        migrations.AlterField(
            model_name='localagentheartbeat',
            name='recent_errors',
            field=models.JSONField(blank=True, default=list, help_text='Liste des N dernières erreurs (max 20 items).'),
        ),
        migrations.AlterField(
            model_name='localagentheartbeat',
            name='sent_at',
            field=models.DateTimeField(db_index=True, help_text='Timestamp de génération côté agent.'),
        ),
        migrations.AlterField(
            model_name='localagentheartbeat',
            name='state',
            field=models.CharField(choices=[('installing', 'Installation en cours'), ('starting', 'Démarrage'), ('running', "En cours d'exécution"), ('degraded', 'Dégradé (erreurs)'), ('stopped', 'Arrêté'), ('crashed', 'Crashé'), ('updating', 'Mise à jour en cours'), ('disabled', 'Désactivé (admin)'), ('unreachable', 'Injoignable')], default='running', max_length=16),
        ),
        migrations.AlterField(
            model_name='localagentlog',
            name='source',
            field=models.CharField(blank=True, help_text='Module/component source (ex: "mqtt.client", "driver.hikvision")', max_length=64),
        ),
        migrations.AlterField(
            model_name='localagenttype',
            name='capabilities',
            field=models.JSONField(blank=True, default=list, help_text='Codes capacités ex: ["read_uid", "write_uid", "presence"].'),
        ),
        migrations.AlterField(
            model_name='localagenttype',
            name='code',
            field=models.CharField(choices=[('rfid', 'Agent RFID (UHF / NFC)'), ('ble', 'Agent BLE (casques)'), ('camera', 'Agent Caméra (ONVIF / RTSP)'), ('biometric', 'Agent Biométrique'), ('attendance', 'Agent Terminal de pointage'), ('mqtt', 'Agent MQTT (broker relay)'), ('sync', 'Agent de synchronisation'), ('discovery', 'Agent de découverte réseau'), ('monitoring', 'Agent de monitoring'), ('generic', 'Agent constructeur générique')], db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='localagenttype',
            name='config_schema',
            field=models.JSONField(blank=True, default=dict, help_text="JSON Schema pour valider config à l'attribution."),
        ),
        migrations.AlterField(
            model_name='localagenttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='localagenttype',
            name='is_system',
            field=models.BooleanField(default=False, help_text='True = type de base non supprimable.'),
        ),
        migrations.AlterField(
            model_name='localagenttype',
            name='module_name',
            field=models.CharField(help_text='Ex: "kshield_agent.agents.rfid" (Python) ou "internal/agents/rfid" (Go).', max_length=120),
        ),
        migrations.AddIndex(
            model_name='devicediscovery',
            index=models.Index(fields=['mac_address'], name='devices_dev_mac_add_cfddd0_idx'),
        ),
    ]
