# Generated by Django 4.2.30 on 2026-05-07 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_location',
            field=models.CharField(choices=[('field', 'Chantier'), ('office', 'Bureau'), ('both', 'Bureau + chantiers')], default='office', help_text="Détermine si l'employé requiert un couplage badge + casque RFID sur les chantiers.", max_length=8),
        ),
        migrations.CreateModel(
            name='FaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('embedding_model', models.CharField(choices=[('facenet_v1', 'FaceNet (TF) — 128D'), ('arcface_r100', 'ArcFace IResNet100 — 512D'), ('insightface', 'InsightFace buffalo_l — 512D')], default='facenet_v1', max_length=20)),
                ('embedding', models.JSONField(help_text="Vecteur d'embedding (liste de floats sérialisée). À chiffrer en prod.")),
                ('embedding_dim', models.PositiveSmallIntegerField(default=128)),
                ('quality_score', models.FloatField(default=0.0, help_text="Score qualité de l'image source (0–1). Seuil minimal recommandé : 0.6.")),
                ('threshold', models.FloatField(default=0.6, help_text='Seuil de similarité (0–1) pour valider un match. 0.40 = tolérant. 0.60 = sécurité (défaut KAYDAN). Plancher dur du service : 0.55.')),
                ('source_image', models.ImageField(blank=True, help_text='Image originale chiffrée (S3/MinIO). Référence uniquement.', null=True, upload_to='employees/faces/')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('last_matched_at', models.DateTimeField(blank=True, null=True)),
                ('match_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_profiles', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'indexes': [models.Index(fields=['employee', 'is_active'], name='employees_f_employe_7bec2a_idx')],
            },
        ),
    ]
