# Generated by Django 5.2.14 on 2026-07-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_employee_work_location_faceprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="address",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="employee",
            name="city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="employee",
            name="country_of_residence",
            field=models.CharField(blank=True, default="Côte d'Ivoire", max_length=64),
        ),
        migrations.AddField(
            model_name="employee",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact_relation",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Homme"), ("female", "Femme"), ("other", "Autre")],
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="id_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="id_issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="id_number",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="employee",
            name="id_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cni", "CNI"),
                    ("passport", "Passeport"),
                    ("driver", "Permis"),
                    ("cedeao", "CEDEAO"),
                    ("other", "Autre"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Célibataire"),
                    ("married", "Marié(e)"),
                    ("divorced", "Divorcé(e)"),
                    ("widowed", "Veuf/veuve"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="nationality",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="employee",
            name="neighborhood",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
