# Generated by Django 4.2.30 on 2026-05-07 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo de la filiale (imprimé sur les badges employés).', null=True, upload_to='companies/logos/'),
        ),
        migrations.CreateModel(
            name='SiteGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('code', models.SlugField(max_length=40)),
                ('hardware', models.CharField(choices=[('rpi', 'Raspberry Pi'), ('nuc', 'Intel NUC'), ('mini_pc', 'Mini-PC'), ('edge_box', 'Edge Box (industriel)'), ('vm', 'Machine virtuelle')], default='mini_pc', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('offline', 'Hors ligne'), ('syncing', 'Synchronisation'), ('error', 'Erreur'), ('decommissioned', 'Mis hors service')], default='active', max_length=16)),
                ('lan_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('vpn_endpoint', models.CharField(blank=True, max_length=240)),
                ('api_port', models.PositiveSmallIntegerField(default=8080)),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=120)),
                ('mac_address', models.CharField(blank=True, max_length=20)),
                ('os_version', models.CharField(blank=True, max_length=80)),
                ('kshield_version', models.CharField(blank=True, max_length=40)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('sync_pending_count', models.PositiveIntegerField(default=0)),
                ('api_secret_hash', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gateway', to='sites.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateways', to='core.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gateway locale',
                'verbose_name_plural': 'Gateways locales',
                'ordering': ['name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
    ]
