# Kaydan Shield — Mosquitto config.
# En prod : ajouter TLS + authentification par user/mdp ou certificats client.

listener 1883 0.0.0.0
listener 8883 0.0.0.0

# En dev on autorise l'anonyme ; en prod pointer un password_file :
# password_file /mosquitto/config/passwd
# allow_anonymous false
allow_anonymous true

persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
