# Generated by Django 5.2.14 on 2026-07-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ouvriers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="address",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="worker",
            name="city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="worker",
            name="country_of_residence",
            field=models.CharField(blank=True, default="Côte d'Ivoire", max_length=64),
        ),
        migrations.AddField(
            model_name="worker",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="worker",
            name="emergency_contact_relation",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="worker",
            name="ended_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="worker",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Homme"), ("female", "Femme"), ("other", "Autre")],
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="hired_at",
            field=models.DateField(
                blank=True, help_text="Date de première affectation", null=True
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="id_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="worker",
            name="id_issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="worker",
            name="id_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cni", "CNI"),
                    ("passport", "Passeport"),
                    ("driver", "Permis de conduire"),
                    ("cedeao", "CEDEAO"),
                    ("other", "Autre"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Célibataire"),
                    ("married", "Marié(e)"),
                    ("divorced", "Divorcé(e)"),
                    ("widowed", "Veuf/veuve"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="nationality",
            field=models.CharField(
                blank=True, help_text="Ex: Ivoirien, Malien…", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="neighborhood",
            field=models.CharField(
                blank=True, help_text="Quartier / commune", max_length=120
            ),
        ),
    ]
