# Generated by Django 5.2.14 on 2026-06-16 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_executive_digest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="executivedigest",
            new_name="reports_exe_status_e74c83_idx",
            old_name="exec_dig_status_ts_idx",
        ),
        migrations.AddField(
            model_name="executivedigest",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="executivedigest",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="executivedigest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="executivedigest",
            name="executive_summary",
            field=models.TextField(
                blank=True, help_text="2-3 paragraphes destinés au CEO/COO."
            ),
        ),
        migrations.AlterField(
            model_name="executivedigest",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="executivedigest",
            name="raw_metrics",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Snapshot des KPI utilisés pour générer le digest.",
            ),
        ),
    ]
