# Generated by Django 5.2.13 on 2026-04-30 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConformityRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('evacuation_drill', "Exercice d'évacuation"), ('equipment_check', 'Contrôle équipement'), ('inspection', 'Inspection'), ('audit', 'Audit'), ('other', 'Autre')], max_length=24)),
                ('title', models.CharField(max_length=240)),
                ('performed_at', models.DateTimeField()),
                ('performed_by', models.CharField(blank=True, max_length=240)),
                ('result', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='conformity/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conformity_registers', to='sites.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conformity_registers', to='core.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_holder_kind', models.CharField(blank=True, max_length=12)),
                ('subject_holder_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('rgpd_export', 'Export RGPD'), ('rgpd_forget', 'Effacement RGPD'), ('operational', 'Export opérationnel')], default='operational', max_length=24)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('ready', 'Prête'), ('delivered', 'Livrée'), ('failed', 'Échec')], default='pending', max_length=12)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('file', models.FileField(blank=True, null=True, upload_to='exports/')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_requests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_requests', to='core.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Mise à jour'), ('delete', 'Suppression'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('export', 'Export'), ('acknowledge', 'Acquittement'), ('override', 'Surcharge manuelle'), ('unlock_door', 'Déverrouillage porte'), ('api_access', 'Accès API')], max_length=24)),
                ('target_model', models.CharField(blank=True, max_length=120)),
                ('target_id', models.CharField(blank=True, max_length=80)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('previous_hash', models.CharField(blank=True, max_length=128)),
                ('hash', models.CharField(blank=True, db_index=True, max_length=128)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['target_model', 'target_id'], name='audit_audit_target__573821_idx')],
            },
        ),
        migrations.CreateModel(
            name='LegalRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_model', models.CharField(max_length=120)),
                ('retention_days', models.PositiveIntegerField()),
                ('legal_basis', models.CharField(blank=True, max_length=240)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_policies', to='core.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tenant', 'target_model')},
            },
        ),
    ]
