# Generated by Django 5.2.13 on 2026-04-30 15:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules_evaluated', models.JSONField(blank=True, default=list)),
                ('deciding_rule_code', models.CharField(blank=True, max_length=80)),
                ('risk_score', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('badge_uid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('helmet_uid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('holder_kind', models.CharField(choices=[('employee', 'Employé'), ('worker', 'Ouvrier'), ('visitor', 'Visiteur'), ('unknown', 'Inconnu')], default='unknown', max_length=12)),
                ('holder_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('direction', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie'), ('pass', 'Passage')], default='in', max_length=8)),
                ('method', models.CharField(choices=[('nfc', 'NFC'), ('uhf', 'UHF'), ('ble', 'BLE'), ('qr', 'QR'), ('manual', 'Manuel')], default='nfc', max_length=8)),
                ('decision', models.CharField(choices=[('granted', 'Accordé'), ('denied', 'Refusé'), ('review', 'À vérifier')], default='granted', max_length=8)),
                ('denial_reason', models.CharField(blank=True, max_length=240)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=180)),
                ('type', models.CharField(choices=[('time_window', 'Plage horaire'), ('zone_authorization', 'Autorisation de zone'), ('pairing_required', 'Appairage badge/casque requis'), ('certification_required', 'Certification HSE requise'), ('escort_required', 'Escorte obligatoire'), ('watchlist', 'Liste rouge'), ('custom', 'Règle personnalisée')], max_length=24)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Avertissement'), ('critical', 'Critique')], default='warning', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('actions', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['site', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DoorCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('command', models.CharField(choices=[('unlock', 'Déverrouiller'), ('lock', 'Verrouiller')], default='unlock', max_length=8)),
                ('status', models.CharField(choices=[('queued', 'En file'), ('sent', 'Envoyée'), ('acknowledged', 'Reçue'), ('succeeded', 'Succès'), ('failed', 'Échec')], default='queued', max_length=14)),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QRCodeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=uuid.uuid4, max_length=120, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField()),
                ('single_use', models.BooleanField(default=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
