# Generated by Django 5.2.13 on 2026-04-30 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        ('devices', '0001_initial'),
        ('sites', '0001_initial'),
        ('visitors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessevent',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_events', to='devices.device'),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='holder_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant scanné (cas mode mobile)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_events', to='sites.site'),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_events', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_events', to='sites.zone'),
        ),
        migrations.AddField(
            model_name='accessdecision',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision_trace', to='access_control.accessevent'),
        ),
        migrations.AddField(
            model_name='accessrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessrule',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='sites.site'),
        ),
        migrations.AddField(
            model_name='accessrule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='accessrule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doorcommand',
            name='checkpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_commands', to='sites.checkpoint'),
        ),
        migrations.AddField(
            model_name='doorcommand',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doorcommand',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='door_commands', to='devices.device'),
        ),
        migrations.AddField(
            model_name='doorcommand',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='door_commands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doorcommand',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='door_commands', to='access_control.accessevent'),
        ),
        migrations.AddField(
            model_name='doorcommand',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qrcodetoken',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qrcodetoken',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qrcodetoken',
            name='visit_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='visitors.visitrequest'),
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['tenant', 'timestamp'], name='access_cont_tenant__da0667_idx'),
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['site', 'timestamp'], name='access_cont_site_id_d19de1_idx'),
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['badge_uid', 'timestamp'], name='access_cont_badge_u_c735c8_idx'),
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['decision', 'timestamp'], name='access_cont_decisio_954e32_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accessrule',
            unique_together={('tenant', 'site', 'code')},
        ),
    ]
