# Generated by Django 5.2.14 on 2026-06-16 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0004_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="accessevent",
            name="acc_evt_site_ts_idx",
        ),
        migrations.RemoveIndex(
            model_name="accessevent",
            name="acc_evt_badge_ts_idx",
        ),
        migrations.RemoveIndex(
            model_name="accessevent",
            name="acc_evt_helmet_ts_idx",
        ),
        migrations.RemoveIndex(
            model_name="accessevent",
            name="acc_evt_decision_ts_idx",
        ),
    ]
