# Generated by Django 4.2.30 on 2026-05-10 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSORoleMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keycloak_role', models.CharField(db_index=True, help_text='Nom du rôle realm ou client dans Keycloak.', max_length=120, unique=True)),
                ('auto_assign_on_login', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('local_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_mappings', to='accounts.role')),
            ],
            options={
                'verbose_name': 'Mapping rôle SSO',
                'verbose_name_plural': 'Mappings rôles SSO',
            },
        ),
        migrations.CreateModel(
            name='EdgeSSOSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('users_pushed', models.PositiveIntegerField(default=0)),
                ('users_revoked', models.PositiveIntegerField(default=0)),
                ('error_message', models.CharField(blank=True, max_length=400)),
                ('ok', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_syncs', to='sites.site')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SSOSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_state', models.CharField(db_index=True, help_text="Claim 'session_state' Keycloak — utilisé pour le back-channel logout.", max_length=128)),
                ('access_token_jti', models.CharField(blank=True, db_index=True, max_length=128)),
                ('refresh_token_jti', models.CharField(blank=True, max_length=128)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expirée'), ('revoked', 'Révoquée'), ('logged_out', 'Déconnectée')], default='active', max_length=20)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['session_state', 'status'], name='sso_ssosess_session_3eee41_idx')],
            },
        ),
        migrations.CreateModel(
            name='SSOLoginAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('subject', models.CharField(blank=True, db_index=True, max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('kind', models.CharField(choices=[('login_success', 'Login OK'), ('login_failure', 'Login échec'), ('token_refresh', 'Refresh token'), ('logout', 'Logout'), ('token_invalid', 'Token invalide'), ('user_disabled', 'Utilisateur désactivé'), ('offline_login', 'Login offline')], max_length=24)),
                ('success', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('site', models.ForeignKey(blank=True, help_text='Renseigné pour les login offline depuis une gateway.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sso_audit', to='sites.site')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sso_audit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['subject', 'kind'], name='sso_ssologi_subject_c45d21_idx'), models.Index(fields=['-timestamp', 'kind'], name='sso_ssologi_timesta_e29f5e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SSOIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_index=True, help_text="Claim 'sub' OIDC — identifiant immuable Keycloak.", max_length=128, unique=True)),
                ('issuer', models.CharField(default='', help_text="URL du realm Keycloak (claim 'iss').", max_length=255)),
                ('preferred_username', models.CharField(blank=True, max_length=180)),
                ('email_verified', models.BooleanField(default=False)),
                ('federation_provider', models.CharField(blank=True, help_text="Ex: 'ldap-kaydan', 'entra-kaydan', 'local'.", max_length=80)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sso_identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Identité SSO',
                'verbose_name_plural': 'Identités SSO',
                'indexes': [models.Index(fields=['subject'], name='sso_ssoiden_subject_5283e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='OfflineUserCredentialCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_hash', models.CharField(blank=True, max_length=200)),
                ('badge_uid', models.CharField(blank=True, db_index=True, max_length=80)),
                ('password_hash', models.CharField(blank=True, max_length=200)),
                ('permissions_snapshot', models.JSONField(blank=True, default=list, help_text='Codes de permissions valides au moment de la sync.')),
                ('is_active', models.BooleanField(default=True)),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_caches', to='sites.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_caches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cache user offline',
                'verbose_name_plural': 'Caches users offline',
                'indexes': [models.Index(fields=['site', 'is_active', 'expires_at'], name='sso_offline_site_id_f1e7d6_idx'), models.Index(fields=['badge_uid', 'site'], name='sso_offline_badge_u_a1a82d_idx')],
                'unique_together': {('user', 'site')},
            },
        ),
    ]
