# Generated by Django 5.2.13 on 2026-04-30 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BLEPresencePing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('rssi', models.SmallIntegerField(blank=True, null=True)),
                ('is_immobile', models.BooleanField(default=False)),
                ('accelerometer_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BLEPresenceWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField()),
                ('pings_count', models.PositiveIntegerField(default=0)),
                ('immobile_minutes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('paid', 'Congé payé'), ('sick', 'Maladie'), ('unpaid', 'Sans solde'), ('mission', 'Mission externe'), ('training', 'Formation'), ('other', 'Autre')], default='paid', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé'), ('cancelled', 'Annulé')], default='pending', max_length=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='leave/')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OvertimeCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField()),
                ('base_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_125_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_150_minutes', models.PositiveIntegerField(default=0)),
                ('night_minutes', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OvertimeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('weekly_threshold_hours', models.DecimalField(decimal_places=2, default=40, max_digits=5)),
                ('rate_125', models.DecimalField(decimal_places=2, default=1.25, max_digits=4)),
                ('rate_150', models.DecimalField(decimal_places=2, default=1.5, max_digits=4)),
                ('night_rate', models.DecimalField(decimal_places=2, default=1.5, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Punch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holder_kind', models.CharField(choices=[('employee', 'Employé'), ('worker', 'Ouvrier'), ('visitor', 'Visiteur')], max_length=12)),
                ('holder_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('morning_in', 'Pointage matin entrée'), ('morning_out', 'Pointage matin sortie'), ('evening_in', 'Pointage soir entrée'), ('evening_out', 'Pointage soir sortie'), ('break_in', 'Pause entrée'), ('break_out', 'Pause sortie')], max_length=12)),
                ('status', models.CharField(choices=[('on_time', "À l'heure"), ('late', 'En retard'), ('very_late', 'Très en retard'), ('missing', 'Manquant'), ('manual', 'Saisie manuelle')], default='on_time', max_length=12)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('delay_minutes', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holder_kind', models.CharField(choices=[('employee', 'Employé'), ('worker', 'Ouvrier')], max_length=12)),
                ('holder_object_id', models.PositiveBigIntegerField()),
                ('date', models.DateField(db_index=True)),
                ('expected_start', models.TimeField(blank=True, null=True)),
                ('expected_end', models.TimeField(blank=True, null=True)),
                ('is_present_expected', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holder_kind', models.CharField(choices=[('employee', 'Employé'), ('worker', 'Ouvrier')], max_length=12)),
                ('holder_object_id', models.PositiveBigIntegerField()),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('present', 'Présent'), ('partial', 'Présence partielle'), ('absent', 'Absent'), ('leave', 'En congé'), ('rest_day', 'Jour non travaillé'), ('holiday', 'Férié')], default='absent', max_length=12)),
                ('first_punch_at', models.DateTimeField(blank=True, null=True)),
                ('last_punch_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('delay_total_minutes', models.PositiveIntegerField(default=0)),
                ('helmet_paired', models.BooleanField(default=False)),
                ('incidents_count', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_days', to='sites.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_days', to='core.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(max_length=64)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_corrections', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('attendance_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='attendance.attendanceday')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
