# Generated by Django 5.2.13 on 2026-04-30 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0003_initial'),
        ('attendance', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        ('devices', '0001_initial'),
        ('employees', '0001_initial'),
        ('ouvriers', '0001_initial'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blepresenceping',
            name='helmet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ble_pings', to='devices.helmet'),
        ),
        migrations.AddField(
            model_name='blepresenceping',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ble_pings', to='sites.zone'),
        ),
        migrations.AddField(
            model_name='blepresencewindow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blepresencewindow',
            name='helmet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ble_windows', to='devices.helmet'),
        ),
        migrations.AddField(
            model_name='blepresencewindow',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blepresencewindow',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ble_windows', to='sites.zone'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='ouvriers.worker'),
        ),
        migrations.AddField(
            model_name='overtimecalculation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overtimecalculation',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overtime_calculations', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='overtimecalculation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overtimecalculation',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overtime_calculations', to='ouvriers.worker'),
        ),
        migrations.AddField(
            model_name='overtimerule',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_rules', to='core.company'),
        ),
        migrations.AddField(
            model_name='overtimerule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overtimerule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='punch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='punch',
            name='holder_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='punch',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='punches', to='sites.site'),
        ),
        migrations.AddField(
            model_name='punch',
            name='source_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punches', to='access_control.accessevent'),
        ),
        migrations.AddField(
            model_name='punch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punches', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='punch',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roster',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='sites.site'),
        ),
        migrations.AddField(
            model_name='roster',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='roster',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='attendanceday',
            index=models.Index(fields=['site', 'date', 'status'], name='attendance__site_id_c98ee3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceday',
            unique_together={('tenant', 'site', 'holder_kind', 'holder_object_id', 'date')},
        ),
        migrations.AddIndex(
            model_name='blepresenceping',
            index=models.Index(fields=['helmet', 'timestamp'], name='attendance__helmet__811457_idx'),
        ),
        migrations.AddIndex(
            model_name='punch',
            index=models.Index(fields=['site', 'timestamp'], name='attendance__site_id_b85830_idx'),
        ),
        migrations.AddIndex(
            model_name='punch',
            index=models.Index(fields=['holder_kind', 'holder_object_id', 'timestamp'], name='attendance__holder__fba9bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roster',
            unique_together={('tenant', 'site', 'holder_kind', 'holder_object_id', 'date')},
        ),
    ]
