# Generated by Django 6.0.5 on 2026-05-11 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_face_sighting_confirmation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="facecheckinconfirmation",
            new_name="attendance__date_6a8c49_idx",
            old_name="conf_date_kind_idx",
        ),
        migrations.RenameIndex(
            model_name="facecheckinconfirmation",
            new_name="attendance__status_35bb27_idx",
            old_name="conf_status_idx",
        ),
        migrations.RenameIndex(
            model_name="facesightingevent",
            new_name="attendance__employe_fb245c_idx",
            old_name="sight_emp_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="facesightingevent",
            new_name="attendance__camera__c0f1e3_idx",
            old_name="sight_cam_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="facesightingevent",
            new_name="attendance__matched_7474db_idx",
            old_name="sight_match_ts_idx",
        ),
        migrations.AddField(
            model_name="facecheckinconfirmation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="facecheckinconfirmation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="facesightingevent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="facesightingevent",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="facecheckinconfirmation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="facecheckinconfirmation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="facesightingevent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="facesightingevent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
