# Generated by Django 5.2.14 on 2026-05-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_performance_indexes"),
        (
            "attendance",
            "0004_rename_conf_date_kind_idx_attendance__date_6a8c49_idx_and_more",
        ),
    ]

    operations = []
