# Generated by Django 5.2.14 on 2026-06-16 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_merge_20260513_0905"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="attendanceday",
            name="attday_date_site_idx",
        ),
        migrations.RemoveIndex(
            model_name="attendanceday",
            name="attday_status_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="blepresenceping",
            name="ble_ping_helmet_ts_idx",
        ),
        migrations.RemoveIndex(
            model_name="blepresenceping",
            name="ble_ping_zone_ts_idx",
        ),
        migrations.RemoveIndex(
            model_name="punch",
            name="punch_site_ts_idx",
        ),
        migrations.RemoveIndex(
            model_name="punch",
            name="punch_holder_ts_idx",
        ),
        migrations.RemoveIndex(
            model_name="punch",
            name="punch_type_ts_idx",
        ),
        migrations.RemoveIndex(
            model_name="roster",
            name="roster_date_site_idx",
        ),
    ]
